baseurl = "https://notquiteacbeerblog.mumblecrunch.ca/"
DefaultContentLanguage = "en"
title = "Not (Quite) ACBeerBlog.Ca"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "News & Views about Beer on Canada's East Coast"
  logo = "images/acbblogo.png"
  favicon = "images/acbblogo.png"
  dateFormat = "2006 January _2"
  commit = false
  rss = false
  comments = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  src = "images/cropped-beer-club.jpg"
  desc = "Beer!"
#[[Params.bigimg]]
  #src = "images/gohugo-default-sample-hero-image.jpg"
  #desc = "Hero"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Atlantic Canada Beer Blog"
  email = "acbeerblog@gmail.com"
  facebook = "ACBeerBlog"
  twitter = "ACBeerBlog"
  instagram = "ACBeerBlog"
  #googleplus = ""
  #github = ""
  #reddit = ""
  #linkedin = ""
  #xing = ""
  #stackoverflow = ""
  #snapchat = ""
  #youtube = "" # or channel/channelname
  #soundcloud = ""
  #spotify = ""
  #bandcamp = ""
  #itchio = ""

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    identifier = "resources"
    name = "Resources"
    weight = 2

[[menu.main]]
    parent = "resources"
    name = "Atlantic Canada Good Beer Map"
    url = "page/the-brewnosers-atlantic-canada-good-beer-map"
    weight = 1

[[menu.main]]
    parent = "resources"
    name = "Calendar of Events"
    url = "page/calendar-of-events"
    weight = 2

[[menu.main]]
    parent = "resources"
    name = "Growlers"
    url = "page/growlers"
    weight = 3

[[menu.main]]
    name = "About"
    url = "page/about"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 4

#[[menu.main]]
#    identifier = "samples"
#    name = "Samples"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Big Image Sample"
#    url = "post/2017-03-07-bigimg-sample"
#    weight = 1

#[[menu.main]]
#    parent = "samples"
#    name = "Math Sample"
#    url = "post/2017-03-05-math-sample"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Code Sample"
#    url = "post/2016-03-08-code-sample"
#    weight = 3

